title: AITL-Strategy-Proposal
description: National Strategy & Educational Framework Based on AITL (AI × Control × Physical Systems)
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
show_downloads: false

remote_theme: minima

# CSS読み込み
sass:
  sass_dir: assets/css
  style: compressed
